[package]
name = "rust-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
anyhow = "1.0.97"
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
actix-web = "4.9.0"
